// src/components/forms/elements/AppTextarea.tsx
import React from 'react';
import { useFormContext } from 'react-hook-form';

const AppTextarea = ({ title, inputName, required, className }:{ title:string, inputName:string, required?:boolean, className?:string }) => {

    const { register, formState: { errors } } = useFormContext();
    return (
        <label className='field'>

            {errors[inputName] && <ul className="error-list" >
                <li className="error-item">
                    Это поле обязательно
                </li>
            </ul>}


            <textarea
                {...register(inputName, { required })}          
                className={`field__textarea ${className}`}
                name={inputName}              
                placeholder={title}             
            ></textarea>
            <span className="field__title">
                { title }
            </span>
        </label>
    );
};

export default AppTextarea;

// src/components/forms/elements/AppTextarea.vue
<template>
  <AppValidationProvider
    tag="label"
    class="field"
    :rules="validationRules"
    v-slot="{ errors }"
    :class="{ required }"
  >
    <transition name="height-fade">
      <ul class="error-list" v-if="errors">
        <li class="error-item" :key="error" v-for="error in errors">
          {{ error }}
        </li>
      </ul>
    </transition>

    <textarea
      class="field__textarea"
      v-mask="maskReg"
      :name="inputName"
      :placeholder="title"
      v-model="inputValue"
    ></textarea>
    <span class="field__title">
      {{ title }}
    </span>
  </AppValidationProvider>
</template>

<script>
export default {
  name: 'AppTextarea',

  data() {
    return {
      inputValue: '',
    };
  },

  computed: {
    validationRules() {
      let validations = {};

      this.required ? (validations.required = true) : false;

      return validations;
    },

    maskReg() {
      if (this.mask) {
        switch (this.mask) {
          case 'phone':
            return '+7 (###) ###-##-##';
          default:
            return '';
        }
      } else {
        return '';
      }
    },
  },

  methods: {
    resetElement() {
      this.inputValue = '';
    },
  },

  props: {
    title: {
      type: String,
      required: true,
    },

    inputName: {
      type: String,
      required: true,
    },

    required: {
      type: Boolean,
      default: false,
    },

    mask: {
      type: String,
      default: '',
    },
  },
};
</script>

<style lang="scss" scoped></style>
