// src/components/article/Docs.tsx
interface Doc {
    file: string;
    title: string;
}

interface DocsProps {
    docs: Doc[];
}

const Docs: React.FC<DocsProps> = ({ docs }) => {
    return (
        <div className="mtp__document">
            <div className="mtp__document-header">
                <h3>Документы для скачивания</h3>
                {docs.map((doc, index) => (
                    <a key={index} href={doc.file} download className="mtp__document-item">
                        <div className="mtp__document-content">
                            <i className="icon icon--download"></i>
                            <div className="name">{doc.title}</div>
                        </div>
                    </a>
                ))}
            </div>
        </div>
    );
};

export default Docs;

// src/components/article/Docs.vue
<template>
    <div class="mtp__document">
        <div class="mtp__document-header">
            <h3>Документы для скачивания</h3>
            <a v-for="doc in docs" :key="JSON.stringify(doc)" 
                :href="doc.file" 
                download
                class="mtp__document-item">
                <div class="mtp__document-content">
                    <i class="icon icon--download"></i>
                    <div class="name">{{ doc.title }}</div>
                </div>
            </a>
        </div>
    </div>
</template>

<script>
    export default {
        name: 'AppArticleDocs',
        props: {
            docs: {
                type: Array,
                default: () => [],
            }
        }
    }
</script>
