// src/components/article/Staff.tsx
import { useTranslation } from 'react-i18next';
import { useEffect, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { updateActionStaff } from '@/store/staff';
import { AppDispatch } from '@/config/store';

interface StaffMember {
    name: string;
}

interface State {
    staff: {
        staff: StaffMember[];
    };
}

const Staff: React.FC = () => {
    const dispatch = useDispatch<AppDispatch>();
    const { staff } = useSelector((state: State) => state.staff);

    const { t } = useTranslation();

    const [query, setQuery] = useState('');
    const [filteredStaff, setFilteredStaff] = useState<StaffMember[]>([]);

    function filterStaff() {
        if (query === '') {
            setFilteredStaff(staff);
            return;
        }
        setFilteredStaff(staff.filter(person => person.name.toLowerCase().indexOf(query.toLowerCase()) !== -1));
    }

    function resetSearch() {
        setQuery('');
        filterStaff();
    }

    const init = async () => {
        dispatch(updateActionStaff());
        filterStaff();
    };

    useEffect(() => {
        init();
    }, []);

    return (
        <>
            {staff && staff.length > 0 &&
                <div className="specialists">
                    <div className="search-form js-search-form">
                        <label className="search-form__label">
                            <input type="text"
                                className="search-form__input js-search-form__input"
                                placeholder="Введите имя сотрудника"
                                value={query}
                                onInput={(e) => {
                                    setQuery(e.currentTarget.value);
                                    filterStaff();
                                }} />
                        </label>
                        <div className="search-form__controls">
                            <button type="reset" className="btn search-form__btn search-form__btn--reset js-search-form__btn--reset"
                                onClick={() => resetSearch()}
                                title="Сбросить">
                                <i className="icon icon--close"></i>
                            </button>
                        </div>
                    </div>
                    <ul className="specialists__list">
                        {filteredStaff.map((person, index) => <li key={index} className="specialists__list-item">
                            {person.name}
                        </li>)}
                        <li className="specialists__list-item"
                            style={{ display: (filteredStaff.length !== 0) ? 'none' : 'block' }}>
                            {t('staff.noResults')}
                        </li>
                    </ul>
                </div>
            }
        </>
    );
};

export default Staff;

// src/components/article/Staff.vue
<template>
    <div class="specialists" v-if="staff && staff.length > 0">
        <div class="search-form js-search-form">
            <label class="search-form__label">
                <input type="text" 
                class="search-form__input js-search-form__input" 
                placeholder="Введите имя сотрудника"
                v-model="query"
                @input="filterStaff()" @change="filterStaff()">
            </label>
            <div class="search-form__controls">
                <button type="reset" class="btn search-form__btn search-form__btn--reset js-search-form__btn--reset"
                        @click="resetSearch()"
                        title="Сбросить">
                    <i class="icon icon--close"></i>
                </button>
            </div>
        </div>
        <ul class="specialists__list" v-if="!$fetchState.pending">
            <li class="specialists__list-item" v-for="person in filteredStaff">
                {{ person.name }}
            </li>
            <li class="specialists__list-item" v-show="filteredStaff.length === 0">{{ $t('staff.noResults') }}</li>
        </ul>
    </div>
</template>

<script>
    export default {
        name: 'StaffList',
        data() {
            return {
                query: '',
                filteredStaff: [],
                loaded: false,
            }
        },
        computed: {
            staff() {
                return this.$store.getters['staff/getterStaff'];
            }
        },
        methods: {
            filterStaff() {
                let vm = this;
                if(vm.query === '') {
                    vm.filteredStaff = vm.staff;
                    return;
                }
                vm.filteredStaff = vm.staff.filter(person => person.name.toLowerCase().indexOf(vm.query.toLowerCase()) !== -1);
            },
            resetSearch() {
                let vm = this;
                vm.query = '';
                vm.filterStaff();
            }
        },
        async fetch() {
            await this.$store.dispatch('staff/updateStaff');
            this.filterStaff();
        }
    }
</script>
