// src/components/pages/AppArticles.vue
<template>
    <div>
        <h1>{{ articles.seo_h1 ? articles.seo_h1 : articles.title }}</h1>

        <div class="mtp__news">
            <transition-group tag="div" name="fade" apper class="mtp__news" v-if="
                articles.content &&
                articles.content.length > 0
            ">
                <AppArticlesCard v-for="card in articles.content" :key="card.id" :card="card" />
            </transition-group>

            <AppArticlesPagination :pagination="pagination" />
        </div>
    </div>
</template>
  
<script>

import AppArticlesCard from '@/components/articles/AppArticlesCard.vue';
import AppArticlesPagination from '@/components/articles/AppArticlesPagination.vue';

import head from '@/mixins/head.js';

export default {
    name: 'ArticlesListSlug',

    data() {
        return {
            pageInitial: 1,
            pageSizeInitial: 12,
            orderingInitial: '',
            navigationOrdering: '',
        };
    },
    mixins: [head],

    computed: {
        page() {
            return this.$route.query.page ? this.$route.query.page : 1;
        },

        id() {
            return this.$route.params.pathMatch;
        },

        SEO() {
            return this.$store.getters['pages/getterPagesSeo'];
        },

        ordering() {
            return this.$route.query.ordering ? this.$route.query.ordering : '';
        },

        search() {
            return this.$route.query.search ? this.$route.query.search : '';
        },
        okp() {
            return this.$route.query.okp ? this.$route.query.okp : '';
        },
        tnved() {
            return this.$route.query.tnved ? this.$route.query.tnved : '';
        },

        articles() {
            return this.$store.getters['pages/getterPages'];
        },

        pagination() {
            return {
                page: this.page ?? null,
                next: this.articles.next ?? null,
                prev: this.articles.previous ?? null,
                totalElements: this.articles.totalElements ?? null,
                totalPages: this.articles.totalPages ?? null,
                pageSize: this.articles.pageSize ?? null,
            };
        },
    },

/*     async fetch() {
        this.$store.dispatch('articles/resetActionArticles');

        await this.$store.dispatch('navigation/updateActionNavigation', [
            this.navigationOrdering,
        ]);
    },
 */
    components: {
        AppArticlesCard,
        AppArticlesPagination,
    },
};
</script>

// src/components/pages/AppArticles.tsx
import { useParams, useSearchParams } from "next/navigation";
import { useEffect, useMemo } from "react";
import AppArticlesCard from "../articles/AppArticlesCard";
import { useDispatch, useSelector } from "react-redux";
import AppArticlesPagination from "../articles/AppArticlesPagination";
import { setMetadata } from "@/store/metadata";
import { generateMetadata } from "@/hook/useHead";
import { RootState } from "@/config/store";


const AppArticles: React.FC = () => {
    const searchParams = useSearchParams();
    const page = searchParams.get('page') ? parseInt(searchParams.get('page') as string) : 1;
    const { SEO, pages: articles } = useSelector((state: RootState) => state.pages);
    const ordering = searchParams.get('ordering') || '';
    const search = searchParams.get('search') || '';
    const okp = searchParams.get('okp') || '';
    const tnved = searchParams.get('tnved') || '';

    const pagination = useMemo(() => {
        return {
            page: page ?? null,
            next: articles.next ?? null,
            prev: articles.previous ?? null,
            totalElements: articles.totalElements ?? null,
            totalPages: articles.totalPages ?? null,
            pageSize: articles.pageSize ?? null,
        };
    }, [page, articles]);

    const { configs: configsPure } = useSelector((state: RootState) => state.config);
    const dispatch = useDispatch();

    const configs = useMemo(() => {
        let parsedConf: { [key: string]: string } = {};
        configsPure?.forEach((item) => {
            let key = item.key;
            let value = item.value;
            parsedConf[key] = value;
        });
        return parsedConf;
    }, [configsPure]);

    useEffect(() => {
        dispatch(setMetadata(generateMetadata(configs, SEO)));
    }, [configs, SEO]);

    return (
        <div>
            {(articles.seo_h1 || articles.title) && <h1>{articles.seo_h1 ? articles.seo_h1 : articles.title}</h1>}
            <div className="mtp__news">
                {articles.content && articles.content.length > 0 &&
                    <div className="mtp__news">
                        {articles.content.map(card => (
                            <AppArticlesCard key={card.id} card={card} />
                        ))}
                    </div>
                }
                <AppArticlesPagination pagination={pagination} />
            </div>
        </div>
    );
};

export default AppArticles;
