// src/app/find-out-cost/index.vue
<template>
  <main class="cost-calc wrapper">
    <div class="cost-calc__wrapper" v-if="!$fetchState.pending">
      <AppCalcProgress
        :current-step="currentStep"
        :currentDiscount="discountSum"
        keep-alive
        :keep-alive-props="{ max: 10 }"
      />

      <AppCalcFormWrapper
        :discount="discount"
        :documents="documents"
        :currentStep="currentStep"
        keep-alive
        :keep-alive-props="{ max: 10 }"
      />
    </div>
  </main>  
</template>

<script>
import AppCalcProgress from '../../components/calculation/AppCalcProgress.vue';
import AppCalcFormWrapper from '../../components/calculation/AppCalcFormWrapper.vue';

export default {
  name: 'AppCalculation',
  components: { AppCalcProgress, AppCalcFormWrapper },

  data() {
    return {
      currentStep: 1,
      discountSum: 0,
    };
  },

  computed: {
    discount() {
      return this.$store.getters['documents/getterDiscounts'];
    },

    documents() {
      return this.$store.getters['documents/getterDocuments'];
    },
    
  },

  methods: {
    stepChangeListener() {
      this.$nuxt.$on('stepChange', () => {
        this.currentStep < 3 ? (this.currentStep += 1) : false;
      });
    },

    stepBackListener() {
      this.$nuxt.$on('stepBack', () => {
        this.currentStep > 1 ? (this.currentStep -= 1) : false;
      });
    },

    discountListener() {
      this.$nuxt.$on('changeCurrDiscount', (value) => {
        this.discountSum = value;
      });
    },

    async fetchDocuments() {
      await this.$store.dispatch('documents/updateActionDocuments');
    },

    async fetchDiscounts() {
      await this.$store.dispatch('documents/updateActionDiscounts');
    },
  },

  async fetch() {
    try {
      await this.fetchDocuments();
      await this.fetchDiscounts();
    } catch (error) {
      if (error instanceof Error) console.error(error);
    }
  },

  created() {
    this.stepChangeListener();
    this.discountListener();
    this.stepBackListener();
  },
};
</script>

<style lang="scss">
@import '~assets/styles/cost-calc.scss';
</style>

// src/app/find-out-cost/page.tsx
'use client';
import '@/assets/styles/cost-calc.scss'
import AppCalcFormWrapper from '@/components/calculation/AppCalcFormWrapper';
import AppCalcProgress from '@/components/calculation/AppCalcProgress';
import { updateActionDiscounts, updateActionDocuments } from '@/store/documents';
import { useEffect, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { AppDispatch, RootState } from '@/config/store'

const Page = () => {

    const dispatch = useDispatch<AppDispatch>()


    const { discounts, documents } = useSelector((state: RootState) => state.documents)

    useEffect(() => {
        dispatch(updateActionDocuments())
        dispatch(updateActionDiscounts())
    }, [])

    const { discountSum, currentStep } = useSelector((state: RootState) => state.find_out_cost)


    return (
        <div className="cost-calc wrapper">
            <div className="cost-calc__wrapper" >
                <AppCalcProgress
                    currentStep={currentStep}
                    currentDiscount={discountSum}

                />

                <AppCalcFormWrapper
                    discount={discounts}
                    documents={documents}
                    currentStep={currentStep}

                />
            </div>
        </div>
    );
};

export default Page;
